version: '3.8'

services:
  express-react-client:
    container_name: express-react-client
    restart: unless-stopped
    image: dppatel/express-react-client:latest
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - express-react-server
    networks:
      - example-net
    ports:
      - '80:80'
  
  express-react-server:
    container_name: express-react-server
    restart: unless-stopped
    image: dppatel/express-react-server:latest
    build: 
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    depends_on:
      - express-react-mongo
    networks:
      - example-net
      - internal-net
    ports:
      - '5000:5000'
    env_file:
      - ./.env
  
  express-react-mongo:
    image: mongo:6.0.3
    container_name: express-react-mongo
    restart: unless-stopped
    ports:
      - '27017'
    environment:
      - MONGO_INITDB_DATABASE=usersDB
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    env_file:
      - ./.env
    # volumes:
    #   - ./server/mongo-data:/data/db
    networks:
      - internal-net

networks:
  example-net:
    name: example-net
  internal-net: 
    name: internal-net